apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langfuse
  namespace: langfuse
spec:
  interval: 30m
  chart:
    spec:
      chart: langfuse
      version: "1.0.x"
      sourceRef:
        kind: HelmRepository
        name: langfuse
        namespace: langfuse
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    langfuse:
      # Logging
      logging:
        level: info
        format: json

      # Security - encryption key and salt
      # IMPORTANT: These must be sealed as secrets
      encryptionKey:
        secretKeyRef:
          name: langfuse-secrets
          key: encryptionKey

      salt:
        secretKeyRef:
          name: langfuse-secrets
          key: salt

      # NextAuth secret for session encryption
      nextauth:
        secret:
          secretKeyRef:
            name: langfuse-secrets
            key: nextauthSecret

      # Feature flags
      features:
        telemetryEnabled: true
        signUpDisabled: false
        experimentalFeaturesEnabled: false

      # SMTP for email notifications (optional)
      # smtp:
      #   connectionUrl: ""
      #   fromAddress: ""

      # Resources for web and worker
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi

      replicas: 2

      # Ingress disabled - using Gateway API HTTPRoute instead
      ingress:
        enabled: false

      # S3 configuration via environment variables
      # All S3 values come from langfuse-s3-config secret
      env:
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: langfuse-s3-config
              key: endpoint
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: langfuse-s3-config
              key: access_key
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: langfuse-s3-config
              key: secret_key
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: langfuse-s3-config
              key: bucket
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: langfuse-s3-config
              key: region

    # Web deployment configuration
    web:
      enabled: true
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi

    # Worker deployment configuration
    worker:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi

    # PostgreSQL - use external CloudNativePG cluster
    postgresql:
      deploy: false

    # External PostgreSQL connection
    # Connection details provided via secret
    externalDatabase:
      type: postgres
      host: langfuse-postgres-rw.langfuse.svc.cluster.local
      port: 5432
      database: langfuse
      user: langfuse
      # Password from secret
      existingSecret: langfuse-db-credentials
      existingSecretPasswordKey: password

    # Redis - use bundled for caching
    redis:
      deploy: true
      architecture: standalone
      auth:
        enabled: true
        existingSecret: langfuse-redis-password
        existingSecretPasswordKey: password
      master:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
        persistence:
          enabled: true
          size: 1Gi
          storageClass: ceph-block

    # ClickHouse - analytics database
    clickhouse:
      deploy: true
      shards: 1
      replicaCount: 1
      auth:
        existingSecret: langfuse-clickhouse-password
        existingSecretKey: password
      persistence:
        enabled: true
        size: 10Gi
        storageClass: ceph-block
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 1Gi
      zookeeper:
        enabled: true
        replicaCount: 1
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        persistence:
          enabled: true
          size: 2Gi
          storageClass: ceph-block

    # S3 - disabled, using external Ceph S3
    s3:
      deploy: false

    # Service configuration
    service:
      type: ClusterIP
      port: 3000
