apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: langfuse-postgres
  namespace: langfuse
spec:
  instances: 3

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

  bootstrap:
    initdb:
      database: langfuse
      owner: langfuse
      secret:
        name: langfuse-db-credentials

  storage:
    storageClass: ceph-block
    size: 20Gi

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

  monitoring:
    enabled: true
    podMonitorEnabled: true

  backup:
    barmanObjectStore:
      destinationPath: s3://langfuse-postgres-backups/
      endpointURL: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local
      s3Credentials:
        accessKeyId:
          name: langfuse-postgres-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: langfuse-postgres-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
    retentionPolicy: "30d"

  # Scheduled backups
  backup:
    volumeSnapshot:
      className: ceph-block
    retentionPolicy: "7d"
