---
# Langfuse application secrets (encryption key and salt)
# Generate encryption key: openssl rand -hex 32
# Generate salt: openssl rand -base64 32
#
# To seal:
# kubectl create secret generic langfuse-secrets --namespace=langfuse \
#   --from-literal=encryptionKey=$(openssl rand -hex 32) \
#   --from-literal=salt=$(openssl rand -base64 32) \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
spec:
  encryptedData:
    encryptionKey: PLACEHOLDER_SEAL_WITH_OPENSSL_RAND_HEX_32
    salt: PLACEHOLDER_SEAL_WITH_OPENSSL_RAND_BASE64_32
  template:
    metadata:
      name: langfuse-secrets
      namespace: langfuse
    type: Opaque
---
# PostgreSQL database credentials
# To seal:
# kubectl create secret generic langfuse-db-credentials --namespace=langfuse \
#   --from-literal=username=langfuse \
#   --from-literal=password=$(openssl rand -base64 32) \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-db-credentials
  namespace: langfuse
spec:
  encryptedData:
    username: PLACEHOLDER_SEAL_WITH_USERNAME_LANGFUSE
    password: PLACEHOLDER_SEAL_WITH_RANDOM_PASSWORD
  template:
    metadata:
      name: langfuse-db-credentials
      namespace: langfuse
      labels:
        cnpg.io/reload: "true"
    type: kubernetes.io/basic-auth
---
# Redis password
# To seal:
# kubectl create secret generic langfuse-redis-password --namespace=langfuse \
#   --from-literal=password=$(openssl rand -base64 32) \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-redis-password
  namespace: langfuse
spec:
  encryptedData:
    password: PLACEHOLDER_SEAL_WITH_RANDOM_PASSWORD
  template:
    metadata:
      name: langfuse-redis-password
      namespace: langfuse
    type: Opaque
---
# ClickHouse password
# To seal:
# kubectl create secret generic langfuse-clickhouse-password --namespace=langfuse \
#   --from-literal=password=$(openssl rand -base64 32) \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-clickhouse-password
  namespace: langfuse
spec:
  encryptedData:
    password: PLACEHOLDER_SEAL_WITH_RANDOM_PASSWORD
  template:
    metadata:
      name: langfuse-clickhouse-password
      namespace: langfuse
    type: Opaque
---
# MinIO credentials
# To seal:
# kubectl create secret generic langfuse-minio-credentials --namespace=langfuse \
#   --from-literal=root-user=admin \
#   --from-literal=root-password=$(openssl rand -base64 32) \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-minio-credentials
  namespace: langfuse
spec:
  encryptedData:
    root-user: PLACEHOLDER_SEAL_WITH_ADMIN
    root-password: PLACEHOLDER_SEAL_WITH_RANDOM_PASSWORD
  template:
    metadata:
      name: langfuse-minio-credentials
      namespace: langfuse
    type: Opaque
---
# PostgreSQL S3 backup credentials
# To seal:
# kubectl create secret generic langfuse-postgres-backup-s3 --namespace=langfuse \
#   --from-literal=ACCESS_KEY_ID=<ceph-access-key> \
#   --from-literal=ACCESS_SECRET_KEY=<ceph-secret-key> \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-postgres-backup-s3
  namespace: langfuse
spec:
  encryptedData:
    ACCESS_KEY_ID: PLACEHOLDER_SEAL_WITH_CEPH_ACCESS_KEY
    ACCESS_SECRET_KEY: PLACEHOLDER_SEAL_WITH_CEPH_SECRET_KEY
  template:
    metadata:
      name: langfuse-postgres-backup-s3
      namespace: langfuse
    type: Opaque
