---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
spec:
  encryptedData:
    encryptionKey: AgBZod5FywxL/sxH2MEZ8a7J9QRQ96IzgdTsIO/5wRVbZlOPDT06zwFZbYnvUiV7DH1/aIKTx9HbyabHS5xLACmnoMbN0j2EowJARjBoAOaSjIXuWY3TPctz3YkdryAhJ0/GnVlx02U+BTZE7zMpBcQyPV1CwVgP+k6qqEbciWs2OHX+jmXJUiFKzCLpCQ/EfMASxHlTWII4RXxz/ShcxkzYC2swm5kHJ/SHr6tUxMdoM+9aqqBvkRJX9tfCS2IbO6vouQF+nufPa0ZoGdw7xhuic3zhKFIAIPUgeZGTFnfRXvFvs7qzeOHiay1LRXIRyr0xeLI6B0cSs/F1KI3DQgNOA3fB2JMS81hJ1IoRxFnZORTOtPmAeTpYfETYCcIV+q202/nLDyNH+5l3ISjOtwvhogBh3/Q6+Bi9if9VkY2lmoV+vF3StsXQMdJ8nkzC3uoH3K8ikq5EofcX35kcczWODay01PXOMpP4WDJrMBRrZDxIpJ8MAxeGpnpEZz7ykRlcL9f3UVlFGOg9Bg1I/H403Wi+IQNfEYJI2qJek5BlVMLKzud4oyCxu6+8FKwaoIVnV5zvFCuL+Bur9pNbbje88xWlQgzN8TJpw4KgQJiWGVhcRhlTfSVM3z4aGvRk7CJ0UqiEkixHDISREuovbq0ft2wnSiTXKyENgV/QKQ72ItTfct2Omve6QMuHL+rZ0SDeiqL4gONytEDyXAADIhGJo0qGJuJVQcKzmNHkv0LFayNKrjkTHFkY/BW11qEDZy0Wjc+Q7W+6/qloO8/XOB6a
    salt: AgANrAh6WnabFL3qB5MC9RSmbcgsylcYBP/6p0/B2wJqUIIUM1LD9Ao8e9e3U5tBerjEpEg4d03uDwQzPzXNTtnSZwKyw+00trD31YKlvFTiSnj53Q4xa/lg+jSIRvzWNBlr/c8ybuEefx6/KRGXFRzJ3JGLI78EQjylfw3fDYIBkyZ6sbsmTS2YvRIItDHF7+NHKjqafZgrmMZUP56BgeJmZRvCAb/u4BbjNnGP0yD2q7zTKPVa5HuH5st9CFzxmGjAR9d+0/ICWHIBXiOwtBZmK5WzH1l8I0w4wpJkxG+oiy3Tw9XhG7zfDAa+WQnTrrbrhmkSWfFMm6bbX8Wn34w6wnvtC12d9wMZQluwyGweckVsO/TRPc2SYX8wuhO2476Y4j9mNiXnsP/lYmB7vlCEPQrvaa1LSsJ+DWuOt94x15pJ8NBrz7S0DFbfCQSmHP5H0kcognmRlL5NxU3Vfg1GX8pRepTA68ogm4ZC/GTAF6+vIumAls5S9uV5FGqIoYBb6CDkHPgkucHphRE0woe0rrDxBR46s0MNfrnEIiNJt7lItKBfJxfvYMEZKPUIWySkBQ51LTltIMbS1XcrAi5zlXZoGZ734sDxpHYXuaymg3NTjyg0vd97BghqRIpOtBzOn4MqiuUp5ToNPve7v9yZBwjQfilz2WKVjFjPMy3PhRh4RIHRgOJTmnzO8oj0dncH8mRmvMejd+ASnQ3iqlEHvsBemDkevls8DlE6D2xLsDVkAi7H32xyM8ca3Q==
  template:
    metadata:
      name: langfuse-secrets
      namespace: langfuse
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-db-credentials
  namespace: langfuse
spec:
  encryptedData:
    password: AgBBeqWokmcCsWyE7o5Hr/ZB2CrlGiUJQQTaTczyw17lFs89s5hlNaeul5EKW55gOVYh0m3xmb149mQVTSF2nZilRBq7eSoooZK9u6jR3q5kJm1Iu8noZRMb2MrHZFz6yCYzm3fzvMCLuZKAE+DuwdeD8n0Mt3XamGWTbqc2O3YzodLggNR7dqiwPNa03Y9J3VLtqYkl90/cMoLYVIVQEOWJXkIS93S3FLMxKSP/EiUXdIru1pNGDdGZkB4cW2aY7Sy6lcykZDdmL7IRc3yqlyoPj3GayxYardUf6LcqjfgUFkk9PyQoRSVfyf4SLhff48yWA9x2kVQAV+gBPBsVAMj19A8v23bJtk3j4u5wSJcxi9A4YlQY6aXu8TzKrtLg4ql3fMKvqPEjtB/kU7Th60uCKmsthBjBI44uy6P3cIPjPlEbrHFIQJUnerAhxbHc5IzzFXN6E9lAz3VQmnZ5/1fn1OTWyDYUZTrIAxH2wlfAFlaksZ7Xi11fu4iuCFBp3kMSy1YXlnVX5W0qj9sDxzNP/LI36NSs6cCnxjkMV5ePli+kvpZkRW3uyTU5cy/TtGdiYB10Q0mdxv4lwii+uwxhdUEY4JDrQOh7F+8iNiYWCzSrp3NrU8SplX7yhqT66y+TViH0ga7+K6IinL2/vCe8b6vx2C7CF8WbFgqbp9QW4JYYUO4RxoqUKtjZOf8yVfb9dr7D8vJs2HNuOV2fR4kJ0eDm3YPXB2qfFbHf1JR+YKsf2pG5fMlhYlZ72g==
    username: AgA+Z+rLasPKZvYTnyXom+5eecDYz0NdqUcaeK9+8q9p53sV8GNAvVc/FhF/MfhS5jsi8mKqYygbosj5e6NsWq0gYS00xBKAj1i1j/VCue9xY+IXKCXFUUl2QIN8DzIm38ENcguXvnqpxC9OX+t4+VjsfmLI5pVSuH+lPl93jh/sms3c63EAm6K2jLkLraYI1LNufw8KE9ZP/TabQkyo+QlhQK7nFv7Bs2anXwJLRlgnOY3zj+bTxGfQaE7FSA7F34yJ/YRs/TaQ6qLPyDG726/pQQ70MFmdJvhdcao922Ag+B5spddHQxJq94IGWryj83v8vUepcpE44zKZqvaTh5zuI4Z1+HcelK2z2aYEpu4sBCCKP99MIlKOPuj7Rz3iTH2TVWhG96IM0rJX78H670GlW87TEBb+JE+xZZv8INgkENm7pGK/bc/hbqzWeTYQiPeNZi19xLpqpo4ywDORow6tUzRpLU1U7lujQ8OAsxMxipLx0BLuz1VkoWuFryOuWhqH2SdFNWqFFwO5CovwrBuCTPMDAlCaq/Rhe3i+EZAHFOfPAF/L+N5fOWTmHpvBzzOUkky+pOhtVllt3d/utuLdjc1d8YzeEOR9r/NO8bDO7Hcw0JhHD1SxQiLOn2jkYq31S2sSrEio65USytiRtqw0iWZl0etYKMWx17YDyth91Mj4W88NFgrRReWjeoUqtqEiGtiHKES05g==
  template:
    metadata:
      name: langfuse-db-credentials
      namespace: langfuse
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-redis-password
  namespace: langfuse
spec:
  encryptedData:
    password: AgChdaWGsURSA4WaPGSUiDcBGqn+zw8CW9qJrkyJ852YnhPWxiwsFJFdHvyDL4euJ8Kd9qEJCosvpqHz/TKX7jAg1KY0y8eyccekMe9yFvslZNtPkoETCnck/OPe38sDNcacbnsGBpv1e4q8qr7s98uBDIChpmEdomG9uWKsgQov+fqeHFeL8miSUV6Z6TZUf2ZlWI2h7btd6p8AUyI5+DIXAVgHmmaSU3DsqYZnu+klgWrwXHYuW1zZmImmY1dHSKBdmZlKWY6QoNq9gq5ht9CD67IL3jqwTyv4Md/v9X1Lwd+UV1Tk2DxARcwDFblk4e0IFGsGS/HbX8BXHtKXshi+YrM+gUZJgw/zY/PhnPVsYek6NOLcwti++/N3S0uXBe5g9ji8ETeOOxjPIkaHTVBsNEhXyCqdjQ8FWrTKWc+/GGhhZ8FFjHvSuBvDJ7d0M9tNfaHlDv2NuHeq7K+1MBUKre7PnUfHs/1ToaRvPwntItXqdTKl16W20NkvHTZNNs09TK3YPDn2sfcK3Em5WguOQr25rCBRKJjicMFxXtYbWP/C/NKfeAh6L4g4wTseu/njRKI5bMhDughHJAtCLKpp8QCnuPHL2QYZQddN2APa254hxP6eiwy6e4jhUlVYnHwixKrP3DmbSLFDjSpLLobwdyP+jYHu6Bo0xTmEb3GklKcDnk/H/I8mTS1reQ/qUQjl6iojzjuc62IZyBKK5la7F61lnoM5b7emQ7gW8NG4HthlGtMvHUFbwH9Q4g==
  template:
    metadata:
      name: langfuse-redis-password
      namespace: langfuse
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-clickhouse-password
  namespace: langfuse
spec:
  encryptedData:
    password: AgAPr3yU7oz2achD2u68w1PfCioxiBOdc1b6SuUMshWyfmYbypC0jNKK7xGq3FViEGbm0ihkm99eN3pkcDxvMpasNMTneJYJjejHxAag+WTryWWzVT65uV8rt295KSARIrf1QVfMktcjDmKkj82jNQbwrcd1Yxfndyw2HwApLl0wQNUN1I7cV5IxjiC7ZC8SnW0OI84Ir6mO3PSWNJIeNoMe2m/tXj1x71laRk+evaxwVXzhZ1V9zNG5w4L8evw1hvPosCm8x4JQEXAT8648XwVvWV5sGdcVorW9Px/PItLgQxTxJ/j1k3G2cwyChFQ8Edem4xyoNAUeAE8XtyuTwFpv6C+RuPuZYcWpbaRdvBTlxmLva7wiL+uGSeyc9pcfHvsoOB84sB7T//lwk84n/E5j3Vf4VrckDazgsNfWjXrqo3mqVoxpE4nm1osIpsCKK4G874YQRCUJ6BVp61BYsaMRtsC6LUKc53AwG9Z7nfuOlkE68ymCFtNdW/JRQDhmVjw6DzBoR8DvswchpjfWXpfmOfarzRtwdBp9l4kcIbYSp3ttMcLJmwsmg5ITtBmCFGKtbtTDHJ4DvG9pu9qy5LWWX30Vn1mSSG/0bqKBFH0FtfewRmFeLrLdhiW2MoW5t5as+sQpNgRNNg6aE2OWErLr/xfzXnuUdk6/cmJegga4gNRbSL3ex5Tzw7rmVdM8VFvlF7yFGN1P34xMwdE1BorLaYNFAgPUZ6Js7gyGmhn/ITwLgszIpgQ8SQP+yw==
  template:
    metadata:
      name: langfuse-clickhouse-password
      namespace: langfuse
---
---
# S3 configuration for Ceph RGW
# NOTE: Needs to be sealed with actual Ceph S3 credentials before deployment
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-s3-config
  namespace: langfuse
spec:
  encryptedData:
    endpoint: PLACEHOLDER_NEEDS_SEALING
    access_key: PLACEHOLDER_NEEDS_SEALING
    secret_key: PLACEHOLDER_NEEDS_SEALING
    bucket: PLACEHOLDER_NEEDS_SEALING
    region: PLACEHOLDER_NEEDS_SEALING
  template:
    metadata:
      name: langfuse-s3-config
      namespace: langfuse
